-- ============================================================
-- Student Form Cloud - Supabase / PostgreSQL schema
-- Architecture: HTML + CSS + JavaScript + Supabase Auth/DB
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Profiles / roles
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'admin' check (role in ('admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Main form (one central form by slug)
-- Draft is stored here. Published versions are immutable snapshots.
-- ------------------------------------------------------------
create table if not exists public.forms (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  auto_next boolean not null default true,
  device_name text not null default '',
  slogan text not null default '',
  draft_questions jsonb not null default '[]'::jsonb,
  draft_revision integer not null default 1 check (draft_revision > 0),
  draft_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Immutable published snapshots
-- ------------------------------------------------------------
create table if not exists public.form_versions (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.forms(id) on delete cascade,
  slug text not null,
  version_number integer not null check (version_number > 0),
  title text not null,
  description text not null default '',
  auto_next boolean not null default true,
  device_name text not null default '',
  slogan text not null default '',
  questions jsonb not null default '[]'::jsonb,
  is_published boolean not null default false,
  published_at timestamptz,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(form_id, version_number)
);

create unique index if not exists uq_one_published_version_per_form
  on public.form_versions(form_id)
  where is_published = true;

create index if not exists idx_form_versions_public_slug
  on public.form_versions(slug, is_published);

-- ------------------------------------------------------------
-- Responses
-- search_text is derived from JSON for fast admin search.
-- ------------------------------------------------------------
create table if not exists public.responses (
  id uuid primary key default gen_random_uuid(),
  form_id uuid not null references public.forms(id) on delete cascade,
  form_version_id uuid not null references public.form_versions(id) on delete restrict,
  response jsonb not null default '{}'::jsonb,
  schema_snapshot jsonb not null default '[]'::jsonb,
  device_name text not null default '',
  search_text text generated always as (lower(response::text || ' ' || device_name)) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists idx_responses_form_created
  on public.responses(form_id, created_at desc);

create index if not exists idx_responses_search_text
  on public.responses using gin (to_tsvector('simple', search_text));

-- ------------------------------------------------------------
-- Audit logs
-- ------------------------------------------------------------
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created
  on public.audit_logs(created_at desc);

-- ------------------------------------------------------------
-- Updated-at trigger
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_blank_jsonb_answer(p_value jsonb)
returns boolean
language plpgsql
immutable
as $$
begin
  if p_value is null or p_value = 'null'::jsonb then
    return true;
  end if;

  if jsonb_typeof(p_value) = 'string' and btrim(p_value #>> '{}') = '' then
    return true;
  end if;

  if jsonb_typeof(p_value) = 'array' and jsonb_array_length(p_value) = 0 then
    return true;
  end if;

  return false;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_forms_updated_at on public.forms;
create trigger trg_forms_updated_at
before update on public.forms
for each row execute function public.set_updated_at();

drop trigger if exists trg_responses_updated_at on public.responses;
create trigger trg_responses_updated_at
before update on public.responses
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- Admin role helper
-- Uses SECURITY DEFINER so RLS can safely ask whether the caller
-- is an admin without exposing profile rows to anonymous users.
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ------------------------------------------------------------
-- Condition helper for server-side response validation
-- ------------------------------------------------------------
create or replace function public.condition_matches_response(
  p_response jsonb,
  p_condition jsonb
)
returns boolean
language plpgsql
immutable
as $$
declare
  v_question_id text := p_condition->>'questionId';
  v_operator text := coalesce(p_condition->>'operator', 'eq');
  v_target text := coalesce(p_condition->>'value', '');
  v_value jsonb := p_response->v_question_id;
  v_text text := '';
begin
  if v_value is null or v_value = 'null'::jsonb then
    v_text := '';
  elsif jsonb_typeof(v_value) = 'array' then
    select coalesce(string_agg(value, '، '), '') into v_text
    from jsonb_array_elements_text(v_value);
  else
    v_text := coalesce(v_value #>> '{}', '');
  end if;

  case v_operator
    when 'empty' then return btrim(v_text) = '';
    when 'notempty' then return btrim(v_text) <> '';
    when 'contains' then return position(v_target in v_text) > 0;
    when 'starts' then return left(v_text, length(v_target)) = v_target;
    when 'ends' then return right(v_text, length(v_target)) = v_target;
    when 'neq' then return btrim(v_text) <> btrim(v_target);
    else return btrim(v_text) = btrim(v_target);
  end case;
end;
$$;

-- ------------------------------------------------------------
-- Question visibility helper
-- ------------------------------------------------------------
create or replace function public.question_is_visible(
  p_response jsonb,
  p_question jsonb
)
returns boolean
language plpgsql
immutable
as $$
declare
  v_conditions jsonb := coalesce(p_question->'conditions', '[]'::jsonb);
  v_mode text := coalesce(p_question->>'conditionMode', 'and');
  v_result boolean;
begin
  if jsonb_array_length(v_conditions) = 0 then
    return true;
  end if;

  if v_mode = 'or' then
    select exists (
      select 1
      from jsonb_array_elements(v_conditions) condition
      where public.condition_matches_response(p_response, condition)
    ) into v_result;
  else
    select not exists (
      select 1
      from jsonb_array_elements(v_conditions) condition
      where not public.condition_matches_response(p_response, condition)
    ) into v_result;
  end if;

  return coalesce(v_result, false);
end;
$$;

-- ------------------------------------------------------------
-- Validate and submit a public response.
-- This is SECURITY DEFINER and is the ONLY public write path.
-- ------------------------------------------------------------
create or replace function public.submit_public_response(
  p_form_id uuid,
  p_form_version_id uuid,
  p_response jsonb,
  p_device_name text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_version public.form_versions%rowtype;
  v_question jsonb;
  v_id text;
  v_value jsonb;
  v_text text;
  v_text_ascii text;
  v_validation jsonb;
  v_min numeric;
  v_max numeric;
  v_num numeric;
  v_options jsonb;
  v_schema jsonb;
  v_clean_response jsonb := '{}'::jsonb;
  v_response_id uuid;
begin
  if jsonb_typeof(p_response) <> 'object' then
    raise exception 'پاسخ باید یک شیء JSON باشد.' using errcode = '22023';
  end if;

  select * into v_version
  from public.form_versions
  where id = p_form_version_id
    and form_id = p_form_id
    and is_published = true;

  if not found then
    raise exception 'این نسخه فرم منتشرشده نیست یا وجود ندارد.' using errcode = '42501';
  end if;

  v_schema := v_version.questions;

  -- Reject unknown fields.
  if exists (
    select 1
    from jsonb_object_keys(p_response) key_name
    where not exists (
      select 1
      from jsonb_array_elements(v_schema) q
      where q->>'id' = key_name
    )
  ) then
    raise exception 'پاسخ شامل فیلد ناشناخته است.' using errcode = '22023';
  end if;

  for v_question in select value from jsonb_array_elements(v_schema)
  loop
    v_id := v_question->>'id';
    v_value := p_response->v_id;

    if not public.question_is_visible(p_response, v_question) then
      continue;
    end if;

    if coalesce((v_question->>'required')::boolean, false) then
      if public.is_blank_jsonb_answer(v_value) then
        if jsonb_typeof(v_value) = 'array' then
          raise exception 'حداقل یک گزینه برای سؤال «%» انتخاب کنید.', v_question->>'label' using errcode = '22023';
        end if;
        raise exception 'پاسخ سؤال «%» الزامی است.', v_question->>'label' using errcode = '22023';
      end if;
    end if;

    if public.is_blank_jsonb_answer(v_value) then
      continue;
    end if;

    v_validation := coalesce(v_question->'validation', '{}'::jsonb);
    v_text := coalesce(v_value #>> '{}', '');
    v_text_ascii := translate(v_text, '۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩', '01234567890123456789');

    if v_question->>'type' = 'number' then
      if jsonb_typeof(v_value) <> 'string' or v_text_ascii !~ '^[-+]?[0-9]+([.][0-9]+)?$' then
        raise exception 'مقدار سؤال «%» باید عدد باشد.', v_question->>'label' using errcode = '22023';
      end if;
      v_num := v_text_ascii::numeric;
      if v_validation ? 'min' then
        v_min := (v_validation->>'min')::numeric;
        if v_num < v_min then raise exception 'مقدار «%» کمتر از حد مجاز است.', v_question->>'label' using errcode = '22023'; end if;
      end if;
      if v_validation ? 'max' then
        v_max := (v_validation->>'max')::numeric;
        if v_num > v_max then raise exception 'مقدار «%» بیشتر از حد مجاز است.', v_question->>'label' using errcode = '22023'; end if;
      end if;
      if coalesce((v_validation->>'integer')::boolean, false) and v_num <> trunc(v_num) then
        raise exception 'مقدار «%» باید عدد صحیح باشد.', v_question->>'label' using errcode = '22023';
      end if;
    end if;

    if v_question->>'type' in ('text','textarea','select','radio','date','jalali','serial') then
      if v_validation ? 'minLength' and length(v_text) < (v_validation->>'minLength')::integer then
        raise exception 'طول «%» کمتر از حد مجاز است.', v_question->>'label' using errcode = '22023';
      end if;
      if v_validation ? 'maxLength' and length(v_text) > (v_validation->>'maxLength')::integer then
        raise exception 'طول «%» بیشتر از حد مجاز است.', v_question->>'label' using errcode = '22023';
      end if;
      if v_validation ? 'pattern' and v_text_ascii !~ (v_validation->>'pattern') then
        raise exception 'قالب سؤال «%» صحیح نیست.', v_question->>'label' using errcode = '22023';
      end if;
    end if;

    if v_question->>'type' in ('select','radio') then
      v_options := coalesce(v_question->'options','[]'::jsonb);
      if not exists (
        select 1 from jsonb_array_elements_text(v_options) opt where opt = v_text
      ) then
        raise exception 'گزینه سؤال «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
      end if;
    end if;

    if v_question->>'type' = 'checkbox' then
      v_options := coalesce(v_question->'options','[]'::jsonb);
      if jsonb_typeof(v_value) <> 'array' then
        raise exception 'ساختار پاسخ سؤال «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
      end if;
      if exists (
        select 1
        from jsonb_array_elements_text(v_value) selected
        where not exists (select 1 from jsonb_array_elements_text(v_options) opt where opt = selected)
      ) then
        raise exception 'یکی از گزینه‌های سؤال «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
      end if;
    end if;

    if v_question->>'type' = 'date' and v_text_ascii !~ '^\d{4}-\d{2}-\d{2}$' then
      raise exception 'تاریخ میلادی «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
    end if;

    if v_question->>'type' = 'jalali' and v_text_ascii !~ '^\d{4}/\d{1,2}/\d{1,2}$' then
      raise exception 'تاریخ شمسی «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
    end if;

    if v_question->>'type' = 'serial' and v_text_ascii !~ '^[ابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهی][0-9]{2}/[0-9]{6}$' then
      raise exception 'سریال شناسنامه «%» معتبر نیست.', v_question->>'label' using errcode = '22023';
    end if;

    v_clean_response := v_clean_response || jsonb_build_object(v_id, v_value);
  end loop;

  insert into public.responses(form_id, form_version_id, response, schema_snapshot, device_name)
  values(p_form_id, p_form_version_id, v_clean_response, v_schema, left(coalesce(p_device_name,''),120))
  returning id into v_response_id;

  return v_response_id;
end;
$$;

-- ------------------------------------------------------------
-- Publish draft atomically.
-- ------------------------------------------------------------
create or replace function public.publish_form(p_form_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_form public.forms%rowtype;
  v_next_version integer;
  v_version_id uuid;
begin
  if not public.is_admin() then
    raise exception 'دسترسی مدیر لازم است.' using errcode = '42501';
  end if;

  select * into v_form from public.forms where id = p_form_id for update;
  if not found then raise exception 'فرم پیدا نشد.' using errcode = 'P0002'; end if;

  select coalesce(max(version_number),0)+1 into v_next_version
  from public.form_versions
  where form_id = p_form_id;

  update public.form_versions
  set is_published = false
  where form_id = p_form_id and is_published = true;

  insert into public.form_versions(
    form_id, slug, version_number, title, description, auto_next,
    device_name, slogan, questions, is_published, published_at, published_by
  ) values (
    v_form.id, v_form.slug, v_next_version, v_form.title, v_form.description,
    v_form.auto_next, v_form.device_name, v_form.slogan, v_form.draft_questions,
    true, now(), auth.uid()
  ) returning id into v_version_id;

  return jsonb_build_object(
    'version_id', v_version_id,
    'version_number', v_next_version,
    'published_at', now()
  );
end;
$$;

-- ------------------------------------------------------------
-- Admin helper: delete all responses for one form.
-- ------------------------------------------------------------
create or replace function public.delete_all_form_responses(p_form_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'دسترسی مدیر لازم است.' using errcode = '42501';
  end if;
  delete from public.responses where form_id = p_form_id;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ------------------------------------------------------------
-- Revoke / grant RPC permissions
-- ------------------------------------------------------------
revoke all on function public.submit_public_response(uuid,uuid,jsonb,text) from public;
grant execute on function public.submit_public_response(uuid,uuid,jsonb,text) to anon, authenticated;

revoke all on function public.publish_form(uuid) from public;
grant execute on function public.publish_form(uuid) to authenticated;

revoke all on function public.delete_all_form_responses(uuid) from public;
grant execute on function public.delete_all_form_responses(uuid) to authenticated;

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.forms enable row level security;
alter table public.form_versions enable row level security;
alter table public.responses enable row level security;
alter table public.audit_logs enable row level security;

-- Profiles: own profile + admins can manage profiles.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select to authenticated
using ((select auth.uid()) = id or (select public.is_admin()));

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
for update to authenticated
using ((select auth.uid()) = id or (select public.is_admin()))
with check ((select auth.uid()) = id or (select public.is_admin()));

-- Forms: admin-only.
drop policy if exists forms_admin_select on public.forms;
create policy forms_admin_select on public.forms
for select to authenticated
using ((select public.is_admin()));

drop policy if exists forms_admin_insert on public.forms;
create policy forms_admin_insert on public.forms
for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists forms_admin_update on public.forms;
create policy forms_admin_update on public.forms
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Form versions: public can read only published snapshots; admins can manage all.
drop policy if exists form_versions_public_select on public.form_versions;
create policy form_versions_public_select on public.form_versions
for select to anon, authenticated
using (is_published = true or (select public.is_admin()));

drop policy if exists form_versions_admin_insert on public.form_versions;
create policy form_versions_admin_insert on public.form_versions
for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists form_versions_admin_update on public.form_versions;
create policy form_versions_admin_update on public.form_versions
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Responses: only admins can read/update/delete. Public submissions go through RPC.
drop policy if exists responses_admin_select on public.responses;
create policy responses_admin_select on public.responses
for select to authenticated
using ((select public.is_admin()));

drop policy if exists responses_admin_update on public.responses;
create policy responses_admin_update on public.responses
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists responses_admin_delete on public.responses;
create policy responses_admin_delete on public.responses
for delete to authenticated
using ((select public.is_admin()));

-- Audit logs: admin only.
drop policy if exists audit_logs_admin_select on public.audit_logs;
create policy audit_logs_admin_select on public.audit_logs
for select to authenticated
using ((select public.is_admin()));

drop policy if exists audit_logs_admin_insert on public.audit_logs;
create policy audit_logs_admin_insert on public.audit_logs
for insert to authenticated
with check ((select public.is_admin()) and admin_id = auth.uid());

-- ------------------------------------------------------------
-- Realtime publication. Safe to run repeatedly.
-- ------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname='public' and tablename='forms'
  ) then
    execute 'alter publication supabase_realtime add table public.forms';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname='public' and tablename='form_versions'
  ) then
    execute 'alter publication supabase_realtime add table public.form_versions';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname='public' and tablename='responses'
  ) then
    execute 'alter publication supabase_realtime add table public.responses';
  end if;
end $$;

-- ------------------------------------------------------------
-- Example: after creating the manager in Supabase Auth,
-- insert the matching profile row:
--
-- insert into public.profiles(id, display_name, role)
-- values ('AUTH_USER_UUID', 'مدیر مدرسه', 'admin')
-- on conflict (id) do update set role='admin', display_name='مدیر مدرسه';
-- ------------------------------------------------------------
